// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUt1LAGXKppUopGwWmtNHdIoWiXv3bcGs',
    appId: '1:956925326588:web:d6d06be735cb280f81d379',
    messagingSenderId: '956925326588',
    projectId: 'work-assistant-178cc',
    authDomain: 'work-assistant-178cc.firebaseapp.com',
    storageBucket: 'work-assistant-178cc.firebasestorage.app',
    measurementId: 'G-8W0HB0G2PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvCQw9Hsqgo_qOBMb8ajiFsIhSLR7Q6kw',
    appId: '1:956925326588:android:e4aec1a9c3694ad281d379',
    messagingSenderId: '956925326588',
    projectId: 'work-assistant-178cc',
    storageBucket: 'work-assistant-178cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl4BNOsV5bmPPG9HA55vtk8qY4JHZfMVc',
    appId: '1:956925326588:ios:a63f4ebc30cc267c81d379',
    messagingSenderId: '956925326588',
    projectId: 'work-assistant-178cc',
    storageBucket: 'work-assistant-178cc.firebasestorage.app',
    iosBundleId: 'com.example.aiWorkAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl4BNOsV5bmPPG9HA55vtk8qY4JHZfMVc',
    appId: '1:956925326588:ios:a63f4ebc30cc267c81d379',
    messagingSenderId: '956925326588',
    projectId: 'work-assistant-178cc',
    storageBucket: 'work-assistant-178cc.firebasestorage.app',
    iosBundleId: 'com.example.aiWorkAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUt1LAGXKppUopGwWmtNHdIoWiXv3bcGs',
    appId: '1:956925326588:web:4af2900112ba84e781d379',
    messagingSenderId: '956925326588',
    projectId: 'work-assistant-178cc',
    authDomain: 'work-assistant-178cc.firebaseapp.com',
    storageBucket: 'work-assistant-178cc.firebasestorage.app',
    measurementId: 'G-HG8P4VGN4W',
  );
}
